# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-11-26 19:32:11
"""
import arcpy

def Model():  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    ONT_WSHED_BDRY_SEC_DERIVED = "ONT_WSHED_BDRY_SEC_DERIVED"
    Fishing_Access_Point = "Fishing_Access_Point"

    # Process: Buffer (Buffer) (analysis)
    Fishing_Access_Point_Buffer = "C:\\Users\\Lenovo\\Documents\\ArcGIS\\Projects\\GEO115#Week9\\GEO115#Week9.gdb\\Fishing_Access_Point_Buffer"
    arcpy.analysis.Buffer(in_features=Fishing_Access_Point, out_feature_class=Fishing_Access_Point_Buffer, buffer_distance_or_field="20 Kilometers", dissolve_option="ALL")

    # Process: Intersect (Intersect) (analysis)
    ONT_WSHED_BDRY_SEC_Intersect = "C:\\Users\\Lenovo\\Documents\\ArcGIS\\Projects\\GEO115#Week9\\GEO115#Week9.gdb\\ONT_WSHED_BDRY_SEC_Intersect"
    arcpy.analysis.Intersect(in_features=[[ONT_WSHED_BDRY_SEC_DERIVED, ""], [Fishing_Access_Point_Buffer, ""]], out_feature_class=ONT_WSHED_BDRY_SEC_Intersect)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\Users\\Lenovo\\Documents\\ArcGIS\\Projects\\GEO115#Week9\\GEO115#Week9.gdb", workspace="C:\\Users\\Lenovo\\Documents\\ArcGIS\\Projects\\GEO115#Week9\\GEO115#Week9.gdb"):
        Model()
    # Step 3: Clip the intersect result to a specific area of interest
    # Define the output path for the clipped data
    clipped_output = "C:\\Users\\Lenovo\\Documents\\ArcGIS\\Projects\\GEO115#Week9\\clipped_output"
    # Step 3: Clip the intersect result to a specific area of interest
    # Define the output path for the clipped data
    clipped_output = "C:\\Users\\Lenovo\\Documents\\ArcGIS\\Projects\\GEO115#Week9\\GEO115#Week9.atbx\\clipped_output"